#!/bin/sh
#
# Generate boilerplate for sbt-boilerplate

OUT="$(dirname $0)/$(basename $0 .sh)"

cat > "$OUT" <<EOF
// Pre-generated by $0
package scala.scalanative
package native

import scalanative.runtime.undefined
EOF

for i in $(seq 1 22); do
    escaped_i="$(echo "$i" | sed 's/\([012]\)/##\1/g')"
    cat >> "$OUT" <<EOF

final abstract class CField$i[P, F]
object CField$i {
  implicit def array[T, N <: Nat]: CField$i[CArray[T, N], T] = undefined
  [$i..#implicit def struct1[[#F1#]]: CField${escaped_i}[CStruct1[[#F1#]], F${escaped_i}] = undefined#
  ]
}
EOF
done
