name: "Unix tests env setup"
description: "Used to setup Unix tests environemt"
inputs:
  scala-version:
    description: "Scala version used in the tests"
    required: true
  java-version:
    description: "Java version to use in tests"
    default: "8"
  llvm-version:
    description: "LLVM toolchain version"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: "zulu"
        java-version: ${{inputs.java-version}}
    - name: Calculate binary version
      shell: bash
      run: |
        version=${{ inputs.scala-version }}
        if [[ $version == 2.* ]]; then
          echo "project-version=${binaryVersion/./_}" >> $GITHUB_ENV
        elif [[ $version == "3-next" ]]; then
          echo "project-version=3_next" >> $GITHUB_ENV
        else 
          echo "project-version=3" >> $GITHUB_ENV
        fi

    - name: Install dependencies
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 10
        max_attempts: 10
        retry_on: error
        shell: bash
        command: |
          sudo apt-get update
          sudo apt-get install libgc-dev

    - name: Install explicit LLVM toolchain
      shell: bash
      if: ${{ inputs.llvm-version != '' }}
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        (yes "" || true) | sudo ./llvm.sh ${{ inputs.llvm-version }}
        
    # Loads cache with dependencies created in test-tools job
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/coursier
          ~/.sbt/boot
        key: ${{ runner.os }}-deps-${{ inputs.scala-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
