package salty.ir

object Tag {
  final val Type = 1
  final val Cf   = 1 + Type
  final val Ef   = 1 + Cf
  final val Val  = 1 + Ef
  final val Ref  = 1 + Val

  final val Child      = 1 + Ref
  final val Implements = 1 + Child
  final val Overrides  = 1 + Implements
  final val Belongs    = 1 + Overrides

  final val TyNull    = 1 + Belongs
  final val TyNothing = 1 + TyNull
  final val TyUnit    = 1 + TyNothing
  final val TyBool    = 1 + TyUnit
  final val TyI8      = 1 + TyBool
  final val TyI16     = 1 + TyI8
  final val TyI32     = 1 + TyI16
  final val TyI64     = 1 + TyI32
  final val TyF32     = 1 + TyI64
  final val TyF64     = 1 + TyF32
  final val TyRef     = 1 + TyF64
  final val TySlice   = 1 + TyRef
  final val TyOf      = 1 + TySlice

  final val Start         = 1 + TyOf
  final val Label         = 1 + Start
  final val If            = 1 + Label
  final val Switch        = 1 + If
  final val Try           = 1 + Switch
  final val CaseTrue      = 1 + Try
  final val CaseFalse     = 1 + CaseTrue
  final val CaseConst     = 1 + CaseFalse
  final val CaseDefault   = 1 + CaseConst
  final val CaseException = 1 + CaseDefault
  final val Merge         = 1 + CaseException
  final val Return        = 1 + Merge
  final val Throw         = 1 + Return
  final val Undefined     = 1 + Throw
  final val End           = 1 + Undefined
  final val EfPhi         = 1 + End
  final val Equals        = 1 + EfPhi
  final val Call          = 1 + Equals
  final val Load          = 1 + Call
  final val Store         = 1 + Load
  final val Add           = 1 + Store
  final val Sub           = 1 + Add
  final val Mul           = 1 + Sub
  final val Div           = 1 + Mul
  final val Mod           = 1 + Div
  final val Shl           = 1 + Mod
  final val Lshr          = 1 + Shl
  final val Ashr          = 1 + Lshr
  final val And           = 1 + Ashr
  final val Or            = 1 + And
  final val Xor           = 1 + Or
  final val Eq            = 1 + Xor
  final val Neq           = 1 + Eq
  final val Lt            = 1 + Neq
  final val Lte           = 1 + Lt
  final val Gt            = 1 + Lte
  final val Gte           = 1 + Gt
  final val Trunc         = 1 + Gte
  final val Zext          = 1 + Trunc
  final val Sext          = 1 + Zext
  final val Fptrunc       = 1 + Sext
  final val Fpext         = 1 + Fptrunc
  final val Fptoui        = 1 + Fpext
  final val Fptosi        = 1 + Fptoui
  final val Uitofp        = 1 + Fptosi
  final val Sitofp        = 1 + Uitofp
  final val Ptrtoint      = 1 + Sitofp
  final val Inttoptr      = 1 + Ptrtoint
  final val Bitcast       = 1 + Inttoptr
  final val Cast          = 1 + Bitcast
  final val Box           = 1 + Cast
  final val Unbox         = 1 + Box
  final val Phi           = 1 + Unbox
  final val Is            = 1 + Phi
  final val Alloc         = 1 + Is
  final val Salloc        = 1 + Alloc
  final val Length        = 1 + Salloc
  final val Elem          = 1 + Length
  final val Param         = 1 + Elem
  final val ValueOf       = 1 + Param
  final val ExceptionOf   = 1 + ValueOf
  final val TagOf         = 1 + ExceptionOf
  final val Const         = 1 + TagOf
  final val TagConst      = 1 + Const

  final val Unit          = 1 + TagConst
  final val Null          = 1 + Unit
  final val True          = 1 + Null
  final val False         = 1 + True
  final val I8            = 1 + False
  final val I16           = 1 + I8
  final val I32           = 1 + I16
  final val I64           = 1 + I32
  final val F32           = 1 + I64
  final val F64           = 1 + F32
  final val Str           = 1 + F64

  final val Class     = 1 + Str
  final val Interface = 1 + Class
  final val Module    = 1 + Interface
  final val Declare   = 1 + Module
  final val Define    = 1 + Declare
  final val Field     = 1 + Define
  final val Extern    = 1 + Field

  final val Local  = 1 + Belongs
  final val Global = 1 + Local
  final val Nested = 1 + Global
}
