name: "MacOs tests env setup"
description: "Used to setup MacOS tests environemt"
inputs:
  scala-version:
    description: "Scala version used in the tests"
    required: true
runs:
  using: "composite"
  steps:
    - name: Calculate binary version
      shell: bash
      run: |
        version=${{ inputs.scala-version }}
        binaryVersion=${version%.*}
        echo "binary-version=${binaryVersion}" >> $GITHUB_ENV
        echo "project-version=${binaryVersion/./_}" >> $GITHUB_ENV

    # Loads cache with dependencies created in test-tools job
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/coursier
          ~/.sbt/boot
        key: ${{ runner.os }}-deps-${{ env.binary-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
