name: "MacOs tests env setup"
description: "Used to setup MacOS tests environemt"
inputs:
  scala-version:
    description: "Scala version used in the tests"
    required: true
  java-version:
    description: "Java version to use in tests"
    default: "8"
  llvm-version:
    description: "Custom version of LLVM to use"
  gc: 
    description: "Garbage collector used, might require installing dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: "zulu"
        java-version: ${{inputs.java-version}}
    - name: Calculate binary version
      shell: bash
      run: |
        version=${{ inputs.scala-version }}
        if [[ $version == 2.* ]]; then
          echo "project-version=${binaryVersion/./_}" >> $GITHUB_ENV
        elif [[ $version == "3-next" ]]; then
          echo "project-version=3_next" >> $GITHUB_ENV
        else 
          echo "project-version=3" >> $GITHUB_ENV
        fi
        
    - name: Install common dependencies
      shell: bash
      run: brew install sbt
    
    - name: Install dependencies
      shell: bash
      if: ${{ startsWith(inputs.gc, 'boehm') }}
      run: brew install bdw-gc

    - name: Install explicit LLVM toolchain
      shell: bash
      if: ${{ inputs.llvm-version != '' }}
      run: |
        if [[ "${{ inputs.llvm-version }}" == "latest" ]]; then 
          brew install llvm
        else 
          brew install llvm@${{ inputs.llvm-version }}
        fi

    # Loads cache with dependencies created in test-tools job
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/coursier
          ~/.sbt/boot
        key: ${{ runner.os }}-deps-${{ inputs.scala-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
