#!/bin/bash
# publishSigned or publishLocal
publish=$1
projectVersions=(2_11 2_12 2_13 3)

set -ex
sbt clean

# use the latest versions
for v in ${projectVersions[@]}; do
  sbt -Dsbt.supershell=false \
    +nscplugin$v/$publish `# Compiler plugins` \
    +junitPlugin$v/$publish \
    nativelib$v/$publish `# Native libraries` \
    clib$v/$publish \
    posixlib$v/$publish \
    windowslib$v/$publish \
    javalib$v/$publish \
    auxlib$v/$publish \
    scalalib$v/$publish \
    testInterfaceSbtDefs$v/$publish `# Testing` \
    testInterface$v/$publish \
    testRunner$v/$publish \
    junitRuntime$v/$publish \
    util$v/$publish `# Tools` \
    nir$v/$publish \
    tools$v/$publish 
done

# Publish sbt plugin
sbt -Dsbt.supershell=false \
  sbtScalaNative/$publish
