#!/bin/bash
# publishSigned or publishLocal
publish=$1

set -ex

sbt clean

# use the latest versions
for v in 2.11.12 2.12.15 2.13.6; do
  sbt -Dsbt.supershell=false \
    ++$v \
    nscplugin/$publish \
    junitPlugin/$publish \
    nativelib/$publish \
    clib/$publish \
    posixlib/$publish \
    windowslib/$publish \
    javalib/$publish \
    auxlib/$publish \
    scalalib/$publish \
    testInterfaceSbtDefs/$publish \
    testInterface/$publish \
    junitRuntime/$publish
done

for v in 3.1.0; do 
  sbt -Dsbt.supershell=false \
  ++$v \
  nscplugin/$publish \
  scalalib3/$publish 
done

sbt -Dsbt.supershell=false \
  util/$publish \
  nir/$publish \
  tools/$publish \
  testRunner/$publish \
  sbtScalaNative/$publish
