#!/usr/bin/env bash

set -e

HERE="`dirname $0`"
VERSION=$(sed -nre "s#[[:space:]]*version[^0-9]+([0-9.]+)#\1#p" $HERE/../.scalafmt.conf)
SCALACLI="$HERE/.scala-cli"
SCALAFMT="$SCALACLI fmt --scalafmt-version $VERSION"
CHECK_MODIFIED_ONLY=${CHECK_MODIFIED_ONLY:-false}

# ver for windows works for dos
if [ ! -f $SCALACLI ]; then
  curl https://raw.githubusercontent.com/VirtusLab/scala-cli/refs/heads/main/scala-cli.sh > $SCALACLI
  chmod +x $SCALACLI
fi
echo $HERE
echo $SCALAFMT

if [[ "$CHECK_MODIFIED_ONLY" == "1" ]]; then
  git diff --name-only main | \
    grep -E '.*\.scala$' |
    xargs "$SCALAFMT"
else 
  $SCALAFMT "$@"
fi
