#!/usr/bin/env bash

# set -x

HERE="`dirname $0`"
VERSION="2.4.2"
COURSIER="$HERE/.coursier"
SCALAFMT="$HERE/.scalafmt-$VERSION"

if [ ! -f $COURSIER ]; then
  curl -L -o $COURSIER https://git.io/coursier-cli
  chmod +x $COURSIER
fi

if [ ! -f $SCALAFMT ]; then
  $COURSIER bootstrap org.scalameta:scalafmt-cli_2.12:$VERSION --main org.scalafmt.cli.Cli -o $SCALAFMT
  chmod +x $SCALAFMT
fi

$SCALAFMT "$@"
