name: Check CLA
on: [pull_request]
jobs:
  check-cla:
    runs-on: ubuntu-latest
    steps:
      - uses: scala/cla-checker@v1
        with:
          author: ${{ github.event.pull_request.user.login }}
