name: Check CLA
on: [pull_request]
jobs:
  check-cla:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/check-cla.sh "${{ github.event.pull_request.user.login }}"
