# Flow dedicated to publishing compiler plugins for Scala 3 RC versions
name: Publish Scala 3 compiler plugin
on:
  workflow_dispatch:
    inputs:
      scala-version:
        type: string
        description: "Version of Scala 3 compiler for which plugin should be published"
        default: ""
      scala-native-version:
        type: string
        description: "Tag of Scala Native release which should be used for release"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.scala-native-version }}
      - uses: ./.github/actions/linux-setup-env
        with:
          scala-version: ${{ inputs.scala-version }}
          java-version: 8

      - name: Setup PGP Key
        run: |
          echo -n "$PGP_SECRET" | base64 --decode | gpg --batch --import
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}

      - name: Publish release
        env:
          MAVEN_USER: "${{ secrets.SONATYPE_USER }}"
          MAVEN_PASSWORD: "${{ secrets.SONATYPE_PASSWORD }}"
          PGP_PASSPHRASE: "${{ secrets.PGP_PASSWORD }}"
        run: >
          sbt '
            set crossScalaVersions += "${{ inputs.scala-version }}";
            set nscPlugin.forBinaryVersion("3")/crossScalaVersions += "${{ inputs.scala-version }}";
            set junitPlugin.forBinaryVersion("3")/crossScalaVersions += "${{ inputs.scala-version }}";
            ++${{ inputs.scala-version }} -v; 
            nscplugin3/publishSigned;
            junitPlugin3/publishSigned
          '
